version: '3.7'
services:
 #docker run --env=MYSQL_ROOT_PASSWORD=123 --env=MYSQL_USER=fede --env=MYSQL_PASSWORD=fede --env=MYSQL_DATABASE=pepe -d mariadb:latest
  mariadb:
    image: mariadb:latest
    container_name: mariadb1
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: pepe
#docker run  --env=MYSQL_HOST=mariadb --env=MYSQL_PORT=3306 --env=MYSQL_DB_NAME=pepe --env=MYSQL_USER=root --env=MYSQL_PASSWORD=123 --network=redMariaDB  -p 8080:8080 -d correlativas
  appjava:
    image: javaback:latest
    depends_on:
      - mariadb
    container_name: sprint-java
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mariadb
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: pepe
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    restart: unless-stopped

