version: '3'

services:
  mysql-tabla:
    container_name: mysql-tabla
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: modulo_socios
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  socios-back:
    image: 4lexander/aceleradora_utn:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql-tabla
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-tabla:3306/modulo_socios
      - SPRING_DATASOURCE_USERNAME=usuario
      - SPRING_DATASOURCE_PASSWORD=usuario
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - PORT=8080
      - PATH_IMAGENES=${PATH_IMAGENES}
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
      - ${PATH_IMAGENES}:/app/imagenes

    command: ["/wait-for-it.sh", "mysql-tabla:3306", "--", "java", "-jar", "/app.jar"]

volumes:
  mysql-data: