name: Creacion imagen Docker
on:
  push:
    branches:
      - 'develop'
     # - 'main'
jobs:
  build:
    runs-on: self-hosted

    steps:
     - uses: actions/checkout@v4
     - name: Build and push dockerimage
       run: |
          docker login ghcr.io -u fedealvarenga --password ${{secrets.TOKEN}}
          docker build . --tag ghcr.io/fedealvarenga/backsquad1-dev
          docker push ghcr.io/fedealvarenga/backsquad1-dev
