name: Generar y publicar dockerImage
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4
     - name: Build and push dockerimage
       run: |
          docker login ghcr.io -u fedealvarenga --password ${{secrets.TOKEN}}
          docker build . --tag ghcr.io/fedealvarenga/backsquad1:latest
          docker push ghcr.io/fedealvarenga/backsquad1:latest
